### ISSUE TITLE
Major slow down on 2.1.35+

### ISSUE THREAD

**Issue by kanjieater** [AnKing-VIP/advanced-browser#111]
Long time user of the add-on, but since I've updated anki & the add-on to 2.1.35 it becomes very slow my large collection (500k+ cards). If I disable all special advanced fields, the effect is still the same - queries take about 4 times longer than if the add-on is disabled.

**Comment by hssm** [comment]
Are you building Anki from source? And, if so, is the build [optimized](https://github.com/ankitects/anki/blob/main/docs/linux.md#optimized-builds)?

**Comment by kanjieater** [comment]
No, I'm on the windows 64-bit version using
`Ver 2.1.35 (84dcaa86)
Python 3.8.0 Qt 5.14.2 PyQt 5.14.2`

**Comment by ijgnd** [comment]
fixed in more recent versions
