### ISSUE TITLE
Card Queue and Card Type column broken since 2.1.45 - upload for fix to ankiweb needed

### ISSUE THREAD

**Issue by ijgnd** [AnKing-VIP/advanced-browser#165]
this should be fixed with https://github.com/AnKing-VIP/advanced-browser/commit/4426a4f3151464147672391a8218af7c12bba1a5 from September 2022.

someone needs to upload these changes to ankiweb. 

the new version should only be uploaded to the latest branch index for Anki 2.1.45 or newer.

the latest version on ankiweb for 2.1.45 in 2023-07-01 is from 2022-09-27and does not include these changes.

To build an .ankiaddon file that's suitable for uploading to ankiweb: clone this repo and go into the cloned folrder and run `python3 release.py`.

**Comment by ijgnd** [comment]
@AnKingMed: could you have someone look into this? Thanks

**Comment by AnKingMed** [comment]
@abdnh do you have some time to do this?

**Comment by abdnh** [comment]
Done.

**Comment by ijgnd** [comment]
@AnKingMed @abdnh: thanks for this quick help!
