### ISSUE TITLE
Reset columns to default width

### ISSUE THREAD

**Issue by akavi1** [AnKing-VIP/advanced-browser#169]
Two of my columns are far too wide, so wide that it would take me hours to manually drag to to a normal size. How do I reset them to the default width?
I tried deleting the addon and the widths went back to normal, but when I redownloaded the addon, everything went back to how it was.

**Comment by ijgnd** [comment]
one thing I forgot: Before clicking the "Reset Window Sizes" make sure to have closed all browser windows - otherwise it won't work.

**Comment by ijgnd** [comment]
Two days have passed so I assume the problem has been solved? If not, just reopen the issue. I won't have time to answer before mid December.
